### ISSUE TITLE
Relocate Logout Button, Modify Footer, and Add Shadow UI Effect

### ISSUE THREAD

**Issue by erm111** [NegroSpiritual/StudentClearanceSystem#3]
Issue Description:

Overview:
This issue documents the changes made to the project, which include relocating the logout button, modifying the footer, and adding a shadow UI effect to the login page.

Changes Made:

Relocating Logout Button:

Description: The logout button was relocated from its original position.
Reason: This change was made to improve the user interface and make the logout button more accessible.
Modifying Footer:

Description: Modifications were made to the footer of the application.
Details: Changes in the footer may include design updates, content adjustments, or other improvements.
Reason: The modifications were aimed at enhancing the visual appeal and usability of the application.
Adding Shadow UI Effect to Login Page:

Description: A shadow UI effect was added to the login page.
Details: This effect involves adding a subtle shadow or depth effect to the login page components, making them stand out and providing a more visually appealing login experience.
Reason: The shadow effect was introduced to enhance the aesthetics of the login page and improve the overall user experience.
Additional Information:

Project Version: Specify the version or branch of the project where these changes were made.
Screenshots: If applicable, attach screenshots that showcase the relocated logout button, modified footer, and the shadow UI effect on the login page.
Related Files/Code:

Include links or references to the relevant code files, such as the CSS or HTML files where the modifications were made.
Testing:

Provide information on how these changes were tested to ensure they function as intended.
Impact:

Explain any potential impact of these modifications on the project, including any known issues or side effects.
Resolution:

Specify how the modifications were resolved, and whether there are any outstanding tasks related to this issue.
Assignees:

Optionally, assign this issue to specific team members or collaborators responsible for reviewing or implementing these changes.
Labels:

Apply appropriate labels to categorize this issue, such as "UI/UX," "Design," "Enhancement," or any other relevant labels.

**Comment by NegroSpiritual** [comment]
LGTM!
